# -*- coding: utf-8 -*-
"""env.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rEgum-IqscuOkAKQ9ASHv9wC6nMHNFsb
"""

#Structure for the environment of the code
import numpy as np
from typing import Tuple

class insulin_env:

  """Insulin environment"""

  def __init__(sensitivity, blood_sugar,insulin_level, daypart):
    """ Initialize environment
    Args:
      sensitivity(int): person's insulin sensitivity based on a value from 1-10
      blood_sugar(float): current blood sugar level 31-300 mg/Dl
      insulin_level(float): 15-236 mIU/L https://emedicine.medscape.com/article/2089224-overview?form=fpf
      daypart(int): indicator of general part of day (0: morning, 1: afternoon, 2: evening, 3: night)
    """
    self.sensitivity = sensitivity
    self.blood_sugar = blood_sugar
    self.time = daypart
    self.insulin_level = insulin_level
    self.state = (sensitivity, blood_sugar,insulin_level, daypart)

  def reset()-> None:
    """resets all parts of the environment"""
    #need to figure out what our 'default state' is here

  def step(state):
    """returns reward from policy"""
      reward, action = policy(state)

    return action, reward